/**
 * convergents-path.component.ts — "The Convergent's Path", the Arena's maze.
 *
 * A perfect maze (exactly one route between any two cells) generated by an
 * iterative recursive-backtracker, seeded with equal amounts of Aether and Nox.
 * Take both in equal measure and walk out the far side; lean too far either way
 * and the realm closes.
 *
 * The maze is generated *iteratively* rather than with recursion: a 13x13 grid
 * is 169 frames of stack, which is survivable, but the depth is proportional to
 * the grid and a larger board on a future difficulty setting would not be.
 *
 * Three input paths, because this is the one game where a keyboard is not
 * enough: arrow keys and WASD, swipes on the board itself, and an on-screen
 * pad that is always present rather than only on touch — a pad that appears
 * based on device sniffing is a pad that is missing on some device you did not
 * think of.
 */
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  NgZone,
  OnDestroy,
  OnInit,
  ViewChild,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ArenaShellComponent } from '../arena-shell.component';
import { ArenaGameBase } from '../arena-game.base';
import { RunResult } from '../arena-scores.service';

type Dir = 'up' | 'down' | 'left' | 'right';

interface Cell {
  /** Walls, clockwise from the top. A carved passage sets both sides false. */
  n: boolean; e: boolean; s: boolean; w: boolean;
  visited: boolean;
}

interface Orb {
  col: number;
  row: number;
  energy: 'aether' | 'nox';
  taken: boolean;
  /** Collection animation, 1 → 0. */
  pop: number;
}

const SIZE = 13;
/** Orbs of each energy. Equal counts, so a perfect balance is always reachable. */
const ORBS_PER_ENERGY = 8;
/**
 * How far out of balance you may drift before the realm closes. Five means a
 * player can always take an orb of either colour without dying outright, and
 * still has to plan two or three moves ahead near the edges.
 */
const COLLAPSE_AT = 5;

const AETHER = '#C9A84C';
const NOX = '#a48bff';

const DELTAS: Record<Dir, { dc: number; dr: number; wall: keyof Cell }> = {
  up:    { dc:  0, dr: -1, wall: 'n' },
  right: { dc:  1, dr:  0, wall: 'e' },
  down:  { dc:  0, dr:  1, wall: 's' },
  left:  { dc: -1, dr:  0, wall: 'w' },
};

const KEY_DIRS: Record<string, Dir> = {
  ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right',
  w: 'up', a: 'left', s: 'down', d: 'right',
  W: 'up', A: 'left', S: 'down', D: 'right',
};

@Component({
  selector: 'app-convergents-path',
  standalone: true,
  imports: [CommonModule, RouterLink, ArenaShellComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './convergents-path.component.html',
  styleUrls: ['../arena-game.css', './convergents-path.component.css'],
})
export class ConvergentsPathComponent extends ArenaGameBase
  implements OnInit, AfterViewInit, OnDestroy {

  readonly gameId = 'convergents-path';
  readonly collapseAt = COLLAPSE_AT;
  readonly totalOrbs = ORBS_PER_ENERGY * 2;

  private readonly cdr = inject(ChangeDetectorRef);
  private readonly zone = inject(NgZone);

  @ViewChild('canvas') canvasRef?: ElementRef<HTMLCanvasElement>;

  phase: 'intro' | 'playing' | 'won' | 'lost' = 'intro';
  aether = 0;
  nox = 0;
  steps = 0;
  seconds = 0;
  result: RunResult | null = null;

  private grid: Cell[] = [];
  private orbs: Orb[] = [];
  private col = 0;
  private row = 0;
  /** Drawn position, in cell units — lerps toward (col,row) for smooth motion. */
  private px = 0;
  private py = 0;
  private ctx: CanvasRenderingContext2D | null = null;
  private raf = 0;
  private last = 0;
  private clock: ReturnType<typeof setInterval> | null = null;
  private reduced = false;
  private cell = 24;
  private originX = 0;
  private originY = 0;
  private touchX = 0;
  private touchY = 0;

  private readonly onKey = (e: KeyboardEvent) => {
    if (this.phase !== 'playing') return;
    const dir = KEY_DIRS[e.key];
    if (!dir) return;
    // Arrow keys scroll the page otherwise, which moves the board out from
    // under the player mid-run.
    e.preventDefault();
    this.zone.run(() => this.move(dir));
  };
  private readonly onResize = () => this.sizeCanvas();

  async ngOnInit(): Promise<void> {
    await this.resolveGate();
    if (this.isBrowser) {
      this.reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    }
    this.cdr.markForCheck();
  }

  ngAfterViewInit(): void {
    if (!this.isBrowser) return;
    window.addEventListener('keydown', this.onKey);
    window.addEventListener('resize', this.onResize, { passive: true });
  }

  ngOnDestroy(): void {
    this.stopLoop();
    this.stopClock();
    if (!this.isBrowser) return;
    window.removeEventListener('keydown', this.onKey);
    window.removeEventListener('resize', this.onResize);
  }

  // ── derived state for the HUD ───────────────────────────────

  get balance(): number { return this.aether - this.nox; }
  get collected(): number { return this.aether + this.nox; }

  /** 0-1 position of the needle: 0 all Nox, 0.5 balanced, 1 all Aether. */
  get needle(): number {
    return 0.5 + (this.balance / (COLLAPSE_AT * 2));
  }

  get drift(): number { return Math.abs(this.balance); }

  get timeLabel(): string {
    const m = Math.floor(this.seconds / 60);
    return `${m}:${String(this.seconds % 60).padStart(2, '0')}`;
  }

  // ── lifecycle ───────────────────────────────────────────────

  start(): void {
    this.phase = 'playing';
    this.aether = 0;
    this.nox = 0;
    this.steps = 0;
    this.seconds = 0;
    this.result = null;
    this.col = this.row = 0;
    this.px = this.py = 0;
    this.generate();
    this.cdr.detectChanges(); // the canvas only exists once `playing` renders
    this.sizeCanvas();

    this.stopClock();
    this.clock = setInterval(() => {
      this.seconds++;
      this.cdr.markForCheck();
    }, 1000);

    this.last = performance.now();
    this.zone.runOutsideAngular(() => {
      this.raf = requestAnimationFrame(t => this.frame(t));
    });
  }

  private stopLoop(): void {
    if (this.raf) cancelAnimationFrame(this.raf);
    this.raf = 0;
  }

  private stopClock(): void {
    if (this.clock) clearInterval(this.clock);
    this.clock = null;
  }

  playAgain(): void {
    this.phase = 'intro';
    this.result = null;
    this.cdr.markForCheck();
  }

  // ── maze generation ─────────────────────────────────────────

  private at(col: number, row: number): Cell {
    return this.grid[row * SIZE + col];
  }

  private generate(): void {
    this.grid = Array.from({ length: SIZE * SIZE }, () => ({
      n: true, e: true, s: true, w: true, visited: false,
    }));

    // Iterative backtracker. `stack` holds the route back to the last cell with
    // an unvisited neighbour, which is what makes the maze perfect: every cell
    // is reached exactly once, so there is exactly one path between any two.
    const stack: Array<[number, number]> = [[0, 0]];
    this.at(0, 0).visited = true;

    while (stack.length) {
      const [c, r] = stack[stack.length - 1];
      const options: Dir[] = [];

      for (const dir of Object.keys(DELTAS) as Dir[]) {
        const { dc, dr } = DELTAS[dir];
        const nc = c + dc, nr = r + dr;
        if (nc < 0 || nr < 0 || nc >= SIZE || nr >= SIZE) continue;
        if (!this.at(nc, nr).visited) options.push(dir);
      }

      if (!options.length) { stack.pop(); continue; }

      const dir = options[Math.floor(Math.random() * options.length)];
      const { dc, dr } = DELTAS[dir];
      const nc = c + dc, nr = r + dr;

      // Carve both sides of the shared wall, or the passage is one-way.
      const from = this.at(c, r);
      const to = this.at(nc, nr);
      if (dir === 'up')    { from.n = false; to.s = false; }
      if (dir === 'down')  { from.s = false; to.n = false; }
      if (dir === 'left')  { from.w = false; to.e = false; }
      if (dir === 'right') { from.e = false; to.w = false; }

      to.visited = true;
      stack.push([nc, nr]);
    }

    this.scatter();
  }

  /** Place the orbs. Start and exit stay clear so neither is a forced pickup. */
  private scatter(): void {
    const free: number[] = [];
    for (let i = 0; i < SIZE * SIZE; i++) {
      if (i === 0 || i === SIZE * SIZE - 1) continue;
      free.push(i);
    }
    for (let i = free.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [free[i], free[j]] = [free[j], free[i]];
    }

    this.orbs = free.slice(0, ORBS_PER_ENERGY * 2).map((idx, n) => ({
      col: idx % SIZE,
      row: Math.floor(idx / SIZE),
      energy: n < ORBS_PER_ENERGY ? 'aether' : 'nox',
      taken: false,
      pop: 0,
    }));
  }

  // ── movement ────────────────────────────────────────────────

  move(dir: Dir): void {
    if (this.phase !== 'playing') return;

    const { dc, dr, wall } = DELTAS[dir];
    if (this.at(this.col, this.row)[wall]) return; // a wall is a wall

    const nc = this.col + dc;
    const nr = this.row + dr;
    if (nc < 0 || nr < 0 || nc >= SIZE || nr >= SIZE) return;

    this.col = nc;
    this.row = nr;
    this.steps++;

    if (this.reduced) { this.px = nc; this.py = nr; }

    const orb = this.orbs.find(o => !o.taken && o.col === nc && o.row === nr);
    if (orb) {
      orb.taken = true;
      orb.pop = 1;
      if (orb.energy === 'aether') this.aether++;
      else this.nox++;

      if (Math.abs(this.balance) >= COLLAPSE_AT) {
        this.lose();
        return;
      }
    }

    if (nc === SIZE - 1 && nr === SIZE - 1) this.win();
    this.cdr.markForCheck();
  }

  /** Swipes: the shorter axis is ignored, so a diagonal drag still resolves. */
  onTouchStart(e: TouchEvent): void {
    const t = e.changedTouches[0];
    this.touchX = t.clientX;
    this.touchY = t.clientY;
  }

  onTouchEnd(e: TouchEvent): void {
    const t = e.changedTouches[0];
    const dx = t.clientX - this.touchX;
    const dy = t.clientY - this.touchY;
    if (Math.abs(dx) < 24 && Math.abs(dy) < 24) return; // a tap, not a swipe
    this.move(
      Math.abs(dx) > Math.abs(dy)
        ? (dx > 0 ? 'right' : 'left')
        : (dy > 0 ? 'down' : 'up')
    );
  }

  // ── endings ─────────────────────────────────────────────────

  private win(): void {
    this.stopLoop();
    this.stopClock();
    this.phase = 'won';

    const drift = Math.abs(this.balance);
    // Quality is what the reward is scaled by: how much of the realm you took,
    // times how evenly you took it. Perfect balance and a full sweep is 1.
    const quality = (this.collected / this.totalOrbs) * (1 - drift / COLLAPSE_AT);
    const score =
      this.collected * 40 +
      Math.max(0, 300 - drift * 100) +
      Math.max(0, 600 - this.seconds * 4);

    const reward = Math.max(10, Math.round((this.game?.xpReward ?? 75) * quality));
    this.result = this.finishRun(Math.max(0, score), true, reward);
    this.cdr.markForCheck();
  }

  private lose(): void {
    this.stopLoop();
    this.stopClock();
    this.phase = 'lost';
    this.result = this.finishRun(this.collected * 20, false);
    this.cdr.markForCheck();
  }

  get perfect(): boolean {
    return this.phase === 'won' && this.balance === 0 && this.collected === this.totalOrbs;
  }

  // ── loop & draw ─────────────────────────────────────────────

  private frame(now: number): void {
    const dt = Math.min((now - this.last) / 1000, 0.05);
    this.last = now;

    // Ease the drawn position toward the logical cell. Frame-rate independent:
    // the same fraction of the remaining distance per second at any refresh.
    const k = 1 - Math.pow(0.0001, dt);
    this.px += (this.col - this.px) * k;
    this.py += (this.row - this.py) * k;

    for (const o of this.orbs) {
      if (o.pop > 0) o.pop = Math.max(0, o.pop - dt * 2.5);
    }

    this.draw();
    this.raf = requestAnimationFrame(t => this.frame(t));
  }

  private draw(): void {
    const ctx = this.ctx;
    if (!ctx) return;
    const s = this.cell;
    const ox = this.originX;
    const oy = this.originY;

    ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

    // Exit glow first, so walls draw over its edges rather than under them.
    const ex = ox + (SIZE - 1) * s;
    const ey = oy + (SIZE - 1) * s;
    const exitGrad = ctx.createRadialGradient(ex + s / 2, ey + s / 2, 0, ex + s / 2, ey + s / 2, s * 1.6);
    exitGrad.addColorStop(0, 'rgba(77, 255, 224, 0.55)');
    exitGrad.addColorStop(1, 'rgba(77, 255, 224, 0)');
    ctx.fillStyle = exitGrad;
    ctx.fillRect(ex - s, ey - s, s * 3, s * 3);

    ctx.strokeStyle = 'rgba(150, 175, 210, 0.55)';
    ctx.lineWidth = 1.5;
    ctx.lineCap = 'round';
    ctx.beginPath();
    for (let r = 0; r < SIZE; r++) {
      for (let c = 0; c < SIZE; c++) {
        const cell = this.at(c, r);
        const x = ox + c * s;
        const y = oy + r * s;
        if (cell.n) { ctx.moveTo(x, y); ctx.lineTo(x + s, y); }
        if (cell.w) { ctx.moveTo(x, y); ctx.lineTo(x, y + s); }
        // Only the last row and column need their far walls drawn; every other
        // cell's south and east wall is its neighbour's north and west.
        if (r === SIZE - 1 && cell.s) { ctx.moveTo(x, y + s); ctx.lineTo(x + s, y + s); }
        if (c === SIZE - 1 && cell.e) { ctx.moveTo(x + s, y); ctx.lineTo(x + s, y + s); }
      }
    }
    ctx.stroke();

    for (const o of this.orbs) {
      if (o.taken && o.pop <= 0) continue;
      const color = o.energy === 'aether' ? AETHER : NOX;
      const cx = ox + o.col * s + s / 2;
      const cy = oy + o.row * s + s / 2;
      const grow = o.taken ? 1 + (1 - o.pop) * 1.6 : 1;
      const alpha = o.taken ? o.pop : 1;

      ctx.globalAlpha = alpha;
      if (!this.reduced) {
        ctx.shadowColor = color;
        ctx.shadowBlur = 10;
      }
      ctx.fillStyle = color;
      ctx.beginPath();
      ctx.arc(cx, cy, s * 0.17 * grow, 0, Math.PI * 2);
      ctx.fill();
      ctx.shadowBlur = 0;
      ctx.globalAlpha = 1;
    }

    // The walker, tinted by whichever energy it is leaning toward.
    const wx = ox + this.px * s + s / 2;
    const wy = oy + this.py * s + s / 2;
    const lean = this.balance;
    const tint = lean === 0 ? '#4dffe0' : lean > 0 ? AETHER : NOX;

    if (!this.reduced) {
      ctx.shadowColor = tint;
      ctx.shadowBlur = 16;
    }
    ctx.fillStyle = tint;
    ctx.beginPath();
    ctx.arc(wx, wy, s * 0.3, 0, Math.PI * 2);
    ctx.fill();
    ctx.shadowBlur = 0;

    ctx.fillStyle = 'rgba(255, 255, 255, 0.85)';
    ctx.beginPath();
    ctx.arc(wx - s * 0.07, wy - s * 0.07, s * 0.1, 0, Math.PI * 2);
    ctx.fill();
  }

  private sizeCanvas(): void {
    const el = this.canvasRef?.nativeElement;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    el.width = Math.round(rect.width * dpr);
    el.height = Math.round(rect.height * dpr);
    this.ctx = el.getContext('2d');
    if (!this.ctx) return;
    this.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    // Square cells, centred, with a half-cell of breathing room so the outer
    // walls are not flush against the canvas edge.
    const pad = 6;
    this.cell = Math.floor((Math.min(rect.width, rect.height) - pad * 2) / SIZE);
    const span = this.cell * SIZE;
    this.originX = Math.round((rect.width - span) / 2);
    this.originY = Math.round((rect.height - span) / 2);
    this.draw();
  }
}
