import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { SITE_URL } from '../seo.service';

const routes: Routes = [
  {
      path: '',
      loadComponent: () => import('../embed-landing/embed-landing.component').then(m => m.EmbedLandingComponent),
      title: 'Embed Developer Tools on Your Site — Free Widgets | xsantcastx',
      data: {
        description: 'Embed free developer tools on your blog, docs, or app. JSON Formatter, Base64 Encoder, Regex Tester, and more. One iframe tag, zero setup.',
        keywords: 'embed developer tools, embeddable widgets, iframe tools, json formatter widget, developer tool embed, free embed',
        jsonLd: {
          '@context': 'https://schema.org',
          '@type': 'WebPage',
          name: 'Embed Developer Tools — xsantcastx',
          description: 'Embed free browser-based developer tools on any website with a single iframe tag.',
          url: `${SITE_URL}/embed`
        }
      }
    },
  { path: 'json-formatter', loadComponent: () => import('./json-formatter/json-formatter.component').then(m => m.JsonFormatterComponent), data: { embed: true } },
  { path: 'base64-encoder', loadComponent: () => import('./base64-encoder/base64-encoder.component').then(m => m.Base64EncoderComponent), data: { embed: true } },
  { path: 'regex-tester', loadComponent: () => import('./regex-tester/regex-tester.component').then(m => m.RegexTesterComponent), data: { embed: true } },
  { path: 'box-shadow-generator', loadComponent: () => import('./box-shadow-generator/box-shadow-generator.component').then(m => m.BoxShadowGeneratorComponent), data: { embed: true } },
  { path: 'color-palette', loadComponent: () => import('./color-palette/color-palette.component').then(m => m.ColorPaletteComponent), data: { embed: true } },
  { path: 'contrast-checker', loadComponent: () => import('./contrast-checker/contrast-checker.component').then(m => m.ContrastCheckerComponent), data: { embed: true } },
  { path: 'image-compressor', loadComponent: () => import('./image-compressor/image-compressor.component').then(m => m.ImageCompressorComponent), data: { embed: true } },
  { path: 'pdf-generator', loadComponent: () => import('./pdf-generator/pdf-generator.component').then(m => m.PdfGeneratorComponent), data: { embed: true } },
  { path: 'gmail-deliverability-checker', loadComponent: () => import('./gmail-deliverability-checker/gmail-deliverability-checker.component').then(m => m.GmailDeliverabilityCheckerComponent), data: { embed: true } },
  { path: 'email-deliverability-auditor', loadComponent: () => import('./email-deliverability-auditor/email-deliverability-auditor.component').then(m => m.EmailDeliverabilityAuditorComponent), data: { embed: true } },
  { path: 'ssl-certificate-inspector', loadComponent: () => import('./ssl-certificate-inspector/ssl-certificate-inspector.component').then(m => m.SslCertificateInspectorComponent), data: { embed: true } },
  { path: 'ssl-certificate-auditor', loadComponent: () => import('./ssl-certificate-auditor/ssl-certificate-auditor.component').then(m => m.SslCertificateAuditorComponent), data: { embed: true } },
  { path: 'svg-to-code', loadComponent: () => import('./svg-to-code/svg-to-code.component').then(m => m.SvgToCodeComponent), data: { embed: true } },
  { path: 'gradient-generator', loadComponent: () => import('./gradient-generator/gradient-generator.component').then(m => m.GradientGeneratorComponent), data: { embed: true } },
  { path: 'jwt-decoder', loadComponent: () => import('./jwt-decoder/jwt-decoder.component').then(m => m.JwtDecoderComponent), data: { embed: true } },
  { path: 'uuid-generator', loadComponent: () => import('./uuid-generator/uuid-generator.component').then(m => m.UuidGeneratorComponent), data: { embed: true } },
  { path: 'hash-generator', loadComponent: () => import('./hash-generator/hash-generator.component').then(m => m.HashGeneratorComponent), data: { embed: true } },
  { path: 'meta-tag-generator', loadComponent: () => import('./meta-tag-generator/meta-tag-generator.component').then(m => m.MetaTagGeneratorComponent), data: { embed: true } },
  { path: 'env-validator', loadComponent: () => import('./env-validator/env-validator.component').then(m => m.EnvValidatorComponent), data: { embed: true } },
  { path: 'font-pairer', loadComponent: () => import('./font-pairer/font-pairer.component').then(m => m.FontPairerComponent), data: { embed: true } },
  { path: 'cron-builder', loadComponent: () => import('./cron-builder/cron-builder.component').then(m => m.CronBuilderComponent), data: { embed: true } },
  { path: 'api-request-builder', loadComponent: () => import('./api-request-builder/api-request-builder.component').then(m => m.ApiRequestBuilderComponent), data: { embed: true } },
  { path: 'json-to-ts', loadComponent: () => import('./json-to-ts/json-to-ts.component').then(m => m.JsonToTsComponent), data: { embed: true } },
  { path: 'markdown-editor', loadComponent: () => import('./markdown-editor/markdown-editor.component').then(m => m.MarkdownEditorComponent), data: { embed: true } },
  { path: 'diff-checker', loadComponent: () => import('./diff-checker/diff-checker.component').then(m => m.DiffCheckerComponent), data: { embed: true } },
  { path: 'timestamp-converter', loadComponent: () => import('./timestamp-converter/timestamp-converter.component').then(m => m.TimestampConverterComponent), data: { embed: true } },
  { path: 'url-encoder', loadComponent: () => import('./url-encoder/url-encoder.component').then(m => m.UrlEncoderComponent), data: { embed: true } },
  { path: 'sql-formatter', loadComponent: () => import('./sql-formatter/sql-formatter.component').then(m => m.SqlFormatterComponent), data: { embed: true } },
  { path: 'base-converter', loadComponent: () => import('./base-converter/base-converter.component').then(m => m.BaseConverterComponent), data: { embed: true } },
  { path: 'password-generator', loadComponent: () => import('./password-generator/password-generator.component').then(m => m.PasswordGeneratorComponent), data: { embed: true } },
  { path: 'qr-generator', loadComponent: () => import('./qr-generator/qr-generator.component').then(m => m.QrGeneratorComponent), data: { embed: true } },
  { path: 'lorem-generator', loadComponent: () => import('./lorem-generator/lorem-generator.component').then(m => m.LoremGeneratorComponent), data: { embed: true } },
  { path: 'color-converter', loadComponent: () => import('./color-converter/color-converter.component').then(m => m.ColorConverterComponent), data: { embed: true } },
  { path: 'case-converter', loadComponent: () => import('./case-converter/case-converter.component').then(m => m.CaseConverterComponent), data: { embed: true } },
  { path: 'flexbox-generator', loadComponent: () => import('./flexbox-generator/flexbox-generator.component').then(m => m.FlexboxGeneratorComponent), data: { embed: true } },
  { path: 'chmod-calculator', loadComponent: () => import('./chmod-calculator/chmod-calculator.component').then(m => m.ChmodCalculatorComponent), data: { embed: true } },
  { path: 'html-entities', loadComponent: () => import('./html-entities/html-entities.component').then(m => m.HtmlEntitiesComponent), data: { embed: true } },
  { path: 'json-path', loadComponent: () => import('./json-path/json-path.component').then(m => m.JsonPathComponent), data: { embed: true } },
  { path: 'css-units', loadComponent: () => import('./css-units/css-units.component').then(m => m.CssUnitsComponent), data: { embed: true } },
  { path: 'aspect-ratio', loadComponent: () => import('./aspect-ratio/aspect-ratio.component').then(m => m.AspectRatioComponent), data: { embed: true } },
  { path: 'css-minifier', loadComponent: () => import('./css-minifier/css-minifier.component').then(m => m.CssMinifierComponent), data: { embed: true } },
  { path: 'http-status', loadComponent: () => import('./http-status/http-status.component').then(m => m.HttpStatusComponent), data: { embed: true } },
  { path: 'border-radius', loadComponent: () => import('./border-radius/border-radius.component').then(m => m.BorderRadiusComponent), data: { embed: true } },
  { path: 'emoji-picker', loadComponent: () => import('./emoji-picker/emoji-picker.component').then(m => m.EmojiPickerComponent), data: { embed: true } },
  { path: 'ip-lookup', loadComponent: () => import('./ip-lookup/ip-lookup.component').then(m => m.IpLookupComponent), data: { embed: true } },
  { path: 'grid-generator', loadComponent: () => import('./grid-generator/grid-generator.component').then(m => m.GridGeneratorComponent), data: { embed: true } },
  { path: 'yaml-json', loadComponent: () => import('./yaml-json/yaml-json.component').then(m => m.YamlJsonComponent), data: { embed: true } },
  { path: 'jwt-generator', loadComponent: () => import('./jwt-generator/jwt-generator.component').then(m => m.JwtGeneratorComponent), data: { embed: true } },
  { path: 'tailwind-lookup', loadComponent: () => import('./tailwind-lookup/tailwind-lookup.component').then(m => m.TailwindLookupComponent), data: { embed: true } },
  { path: 'md-table-generator', loadComponent: () => import('./md-table-generator/md-table-generator.component').then(m => m.MdTableGeneratorComponent), data: { embed: true } },
  { path: 'json-escape', loadComponent: () => import('./json-escape/json-escape.component').then(m => m.JsonEscapeComponent), data: { embed: true } },
  { path: 'animation-generator', loadComponent: () => import('./animation-generator/animation-generator.component').then(m => m.AnimationGeneratorComponent), data: { embed: true } },
  { path: 'text-counter', loadComponent: () => import('./text-counter/text-counter.component').then(m => m.TextCounterComponent), data: { embed: true } },
  { path: 'screen-info', loadComponent: () => import('./screen-info/screen-info.component').then(m => m.ScreenInfoComponent), data: { embed: true } },
  { path: 'slug-generator', loadComponent: () => import('./slug-generator/slug-generator.component').then(m => m.SlugGeneratorComponent), data: { embed: true } },
  { path: 'csv-json', loadComponent: () => import('./csv-json/csv-json.component').then(m => m.CsvJsonComponent), data: { embed: true } },
  { path: 'favicon-generator', loadComponent: () => import('./favicon-generator/favicon-generator.component').then(m => m.FaviconGeneratorComponent), data: { embed: true } },
  { path: 'keyboard-shortcuts', loadComponent: () => import('./keyboard-shortcuts/keyboard-shortcuts.component').then(m => m.KeyboardShortcutsComponent), data: { embed: true } },
  { path: 'placeholder-image', loadComponent: () => import('./placeholder-image/placeholder-image.component').then(m => m.PlaceholderImageComponent), data: { embed: true } },
  { path: 'color-blindness', loadComponent: () => import('./color-blindness/color-blindness.component').then(m => m.ColorBlindnessComponent), data: { embed: true } },
  { path: 'robots-generator', loadComponent: () => import('./robots-generator/robots-generator.component').then(m => m.RobotsGeneratorComponent), data: { embed: true } },
  { path: 'dns-lookup', loadComponent: () => import('./dns-lookup/dns-lookup.component').then(m => m.DnsLookupComponent), data: { embed: true } },
  { path: 'box-model', loadComponent: () => import('./box-model/box-model.component').then(m => m.BoxModelComponent), data: { embed: true } },
  { path: 'snippet-manager', loadComponent: () => import('./snippet-manager/snippet-manager.component').then(m => m.SnippetManagerComponent), data: { embed: true } },
  { path: 'regex-generator', loadComponent: () => import('./regex-generator/regex-generator.component').then(m => m.RegexGeneratorComponent), data: { embed: true } },
  { path: 'text-shadow', loadComponent: () => import('./text-shadow/text-shadow.component').then(m => m.TextShadowComponent), data: { embed: true } },
  { path: 'html-to-md', loadComponent: () => import('./html-to-md/html-to-md.component').then(m => m.HtmlToMdComponent), data: { embed: true } },
  { path: 'data-size', loadComponent: () => import('./data-size/data-size.component').then(m => m.DataSizeComponent), data: { embed: true } },
  { path: 'color-shades', loadComponent: () => import('./color-shades/color-shades.component').then(m => m.ColorShadesComponent), data: { embed: true } },
  { path: 'git-reference', loadComponent: () => import('./git-reference/git-reference.component').then(m => m.GitReferenceComponent), data: { embed: true } },
  { path: 'responsive-preview', loadComponent: () => import('./responsive-preview/responsive-preview.component').then(m => m.ResponsivePreviewComponent), data: { embed: true } },
  { path: 'pomodoro', loadComponent: () => import('./pomodoro/pomodoro.component').then(m => m.PomodoroComponent), data: { embed: true } },
  { path: 'css-filter', loadComponent: () => import('./css-filter/css-filter.component').then(m => m.CssFilterComponent), data: { embed: true } },
  { path: 'npm-search', loadComponent: () => import('./npm-search/npm-search.component').then(m => m.NpmSearchComponent), data: { embed: true } },
  { path: 'json-minifier', loadComponent: () => import('./json-minifier/json-minifier.component').then(m => m.JsonMinifierComponent), data: { embed: true } },
  { path: 'morse-code', loadComponent: () => import('./morse-code/morse-code.component').then(m => m.MorseCodeComponent), data: { embed: true } },
  { path: 'binary-text', loadComponent: () => import('./binary-text/binary-text.component').then(m => m.BinaryTextComponent), data: { embed: true } },
  { path: 'string-repeater', loadComponent: () => import('./string-repeater/string-repeater.component').then(m => m.StringRepeaterComponent), data: { embed: true } },
  { path: 'mock-data', loadComponent: () => import('./mock-data/mock-data.component').then(m => m.MockDataComponent), data: { embed: true } },
  { path: 'apca-contrast', loadComponent: () => import('./apca-contrast/apca-contrast.component').then(m => m.ApcaContrastComponent), data: { embed: true } },
  { path: 'ts-playground', loadComponent: () => import('./ts-playground/ts-playground.component').then(m => m.TsPlaygroundComponent), data: { embed: true } },
  { path: 'caesar-cipher', loadComponent: () => import('./caesar-cipher/caesar-cipher.component').then(m => m.CaesarCipherComponent), data: { embed: true } },
  { path: 'design-tokens', loadComponent: () => import('./design-tokens/design-tokens.component').then(m => m.DesignTokensComponent), data: { embed: true } },
  { path: 'json-schema', loadComponent: () => import('./json-schema/json-schema.component').then(m => m.JsonSchemaComponent), data: { embed: true } },
  { path: 'image-resizer', loadComponent: () => import('./image-resizer/image-resizer.component').then(m => m.ImageResizerComponent), data: { embed: true } },
  { path: 'gradient-text', loadComponent: () => import('./gradient-text/gradient-text.component').then(m => m.GradientTextComponent), data: { embed: true } },
  { path: 'hex-editor', loadComponent: () => import('./hex-editor/hex-editor.component').then(m => m.HexEditorComponent), data: { embed: true } },
  { path: 'sitemap-generator', loadComponent: () => import('./sitemap-generator/sitemap-generator.component').then(m => m.SitemapGeneratorComponent), data: { embed: true } },
  { path: 'seo-checker', loadComponent: () => import('./seo-checker/seo-checker.component').then(m => m.SeoCheckerComponent), data: { embed: true } },
  { path: 'encoding-converter', loadComponent: () => import('./encoding-converter/encoding-converter.component').then(m => m.EncodingConverterComponent), data: { embed: true } },
  { path: 'crontab-ref', loadComponent: () => import('./crontab-ref/crontab-ref.component').then(m => m.CrontabRefComponent), data: { embed: true } },
  { path: 'css-variables', loadComponent: () => import('./css-variables/css-variables.component').then(m => m.CssVariablesComponent), data: { embed: true } },
  { path: 'docker-ref', loadComponent: () => import('./docker-ref/docker-ref.component').then(m => m.DockerRefComponent), data: { embed: true } },
  { path: 'ascii-art', loadComponent: () => import('./ascii-art/ascii-art.component').then(m => m.AsciiArtComponent), data: { embed: true } },
  { path: 'button-generator', loadComponent: () => import('./button-generator/button-generator.component').then(m => m.ButtonGeneratorComponent), data: { embed: true } },
  { path: 'checklist', loadComponent: () => import('./checklist/checklist.component').then(m => m.ChecklistComponent), data: { embed: true } },
  { path: 'color-name', loadComponent: () => import('./color-name/color-name.component').then(m => m.ColorNameComponent), data: { embed: true } },
  { path: 'color-picker', loadComponent: () => import('./color-picker/color-picker.component').then(m => m.ColorPickerComponent), data: { embed: true } },
  { path: 'countdown', loadComponent: () => import('./countdown/countdown.component').then(m => m.CountdownComponent), data: { embed: true } },
  { path: 'gitignore-generator', loadComponent: () => import('./gitignore-generator/gitignore-generator.component').then(m => m.GitignoreGeneratorComponent), data: { embed: true } },
  { path: 'heading-checker', loadComponent: () => import('./heading-checker/heading-checker.component').then(m => m.HeadingCheckerComponent), data: { embed: true } },
  { path: 'hmac-generator', loadComponent: () => import('./hmac-generator/hmac-generator.component').then(m => m.HmacGeneratorComponent), data: { embed: true } },
  { path: 'html-minifier', loadComponent: () => import('./html-minifier/html-minifier.component').then(m => m.HtmlMinifierComponent), data: { embed: true } },
  { path: 'js-minifier', loadComponent: () => import('./js-minifier/js-minifier.component').then(m => m.JsMinifierComponent), data: { embed: true } },
  { path: 'json-diff', loadComponent: () => import('./json-diff/json-diff.component').then(m => m.JsonDiffComponent), data: { embed: true } },
  { path: 'json-tree', loadComponent: () => import('./json-tree/json-tree.component').then(m => m.JsonTreeComponent), data: { embed: true } },
  { path: 'jwt-cheatsheet', loadComponent: () => import('./jwt-cheatsheet/jwt-cheatsheet.component').then(m => m.JwtCheatsheetComponent), data: { embed: true } },
  { path: 'license-picker', loadComponent: () => import('./license-picker/license-picker.component').then(m => m.LicensePickerComponent), data: { embed: true } },
  { path: 'line-sorter', loadComponent: () => import('./line-sorter/line-sorter.component').then(m => m.LinesorterComponent), data: { embed: true } },
  { path: 'mime-lookup', loadComponent: () => import('./mime-lookup/mime-lookup.component').then(m => m.MimeLookupComponent), data: { embed: true } },
  { path: 'og-image-preview', loadComponent: () => import('./og-image-preview/og-image-preview.component').then(m => m.OgImagePreviewComponent), data: { embed: true } },
  { path: 'package-json', loadComponent: () => import('./package-json/package-json.component').then(m => m.PackageJsonComponent), data: { embed: true } },
  { path: 'regex-cheatsheet', loadComponent: () => import('./regex-cheatsheet/regex-cheatsheet.component').then(m => m.RegexCheatsheetComponent), data: { embed: true } },
  { path: 'scroll-snap', loadComponent: () => import('./scroll-snap/scroll-snap.component').then(m => m.ScrollSnapComponent), data: { embed: true } },
  { path: 'spacing-scale', loadComponent: () => import('./spacing-scale/spacing-scale.component').then(m => m.SpacingScaleComponent), data: { embed: true } },
  { path: 'timezone-converter', loadComponent: () => import('./timezone-converter/timezone-converter.component').then(m => m.TimezoneConverterComponent), data: { embed: true } },
  { path: 'transform-playground', loadComponent: () => import('./transform-playground/transform-playground.component').then(m => m.TransformPlaygroundComponent), data: { embed: true } },
  { path: 'transition-generator', loadComponent: () => import('./transition-generator/transition-generator.component').then(m => m.TransitionGeneratorComponent), data: { embed: true } },
  { path: 'ua-parser', loadComponent: () => import('./ua-parser/ua-parser.component').then(m => m.UaParserComponent), data: { embed: true } },
  { path: 'webhook-tester', loadComponent: () => import('./webhook-tester/webhook-tester.component').then(m => m.WebhookTesterComponent), data: { embed: true } },
  { path: 'media-query', loadComponent: () => import('./media-query/media-query.component').then(m => m.MediaQueryComponent), data: { embed: true } },
  { path: 'progress-bar', loadComponent: () => import('./progress-bar/progress-bar.component').then(m => m.ProgressBarComponent), data: { embed: true } },
  { path: 'clip-path', loadComponent: () => import('./clip-path/clip-path.component').then(m => m.ClipPathComponent), data: { embed: true } },
  { path: 'char-map', loadComponent: () => import('./char-map/char-map.component').then(m => m.CharMapComponent), data: { embed: true } },
  { path: 'svg-path-editor', loadComponent: () => import('./svg-path-editor/svg-path-editor.component').then(m => m.SvgPathEditorComponent), data: { embed: true } }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class EmbedRoutingModule {}
