name: Test Secret Injection

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test Secret Availability
        run: |
          if [ ! -z "${{ secrets.BREVO_API_KEY }}" ]; then
            echo "✅ BREVO_API_KEY secret is available"
            echo "Secret length: $(echo '${{ secrets.BREVO_API_KEY }}' | wc -c)"
          else
            echo "❌ BREVO_API_KEY secret is NOT available"
          fi
          
      - name: Test Template Processing
        run: |
          echo "📋 Testing template processing..."
          cp src/environments/environment.prod.template.ts test-env.ts
          
          echo "Before replacement:"
          grep "apiKey:" test-env.ts
          
          # Test the sed command
          sed -i "s|apiKey: '',|apiKey: 'TEST_KEY_REPLACEMENT',|g" test-env.ts
          
          echo "After replacement:"
          grep "apiKey:" test-env.ts
          
          rm test-env.ts